# To see all available options, please visit the docs:
# https://docs.pangolin.net/

gerbil:
    start_port: 51820
    base_endpoint: "<MICHI_PUBLIC_IP>"
    exit_node_name: "michi"

app:
    dashboard_url: "https://pangolin.example.com"
    log_level: "info"

postgres:
    connection_string: postgresql://postgres:<POSTGRES_PASSWORD>@10.88.0.1:5432/postgres

traefik:
    site_types: ["newt"] # Wireguard and local sites are not supported in clustering
    file_mode: true # Pangolin will generate and save yaml files in a shared volume

server:
    secret: "<CLUSTER_SECRET>" # must be identical on every node in the cluster
    cors:
        origins: ["https://pangolin.example.com"]
        methods: ["GET", "POST", "PUT", "DELETE", "PATCH"]
        allowed_headers: ["X-CSRF-Token", "Content-Type"]
        credentials: false
    maxmind_db_path: "./config/GeoLite2-Country.mmdb" # download and place into the config dir
    maxmind_asn_path: "./config/GeoLite2-ASN.mmdb"

flags:
    require_email_verification: false
    disable_signup_without_invite: true
    disable_user_create_org: false
    allow_raw_resources: false
    enable_acme_cert_sync: false
    disable_local_sites: true
    disable_basic_wireguard_sites: true
    disable_config_managed_domains: true
